### ISSUE TITLE
HomevAssistant yaml file error

### ISSUE THREAD

**Issue by sirLeone** [spin877/Bruciatore_BLE#1]
Hi
Great work ! :) But yaml file cannot be compiled and sent to esp32. ESPHome reports error:

![obraz](https://github.com/spin877/Bruciatore_BLE/assets/16336937/557f41b1-7734-4a8e-8c0c-e7af42c9c570)

**Comment by spin877** [comment]
I checked, but I didn't get an error there.

**Comment by sirLeone** [comment]
My fault. YAML is ok and everything works perfect :)
